import { Box, Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = ({}) => {
  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography component="h1" className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Typography>

        <Typography className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </Typography>

        <Box className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Typography component="h2">Documentation &rarr;</Typography>
            <Typography>
              Find in-depth information about Next.js features and API.
            </Typography>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <Typography component="h2">Learn &rarr;</Typography>
            <Typography>
              Learn about Next.js in an interactive course with quizzes!
            </Typography>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <Typography component="h2">Examples &rarr;</Typography>
            <Typography>
              Discover and deploy boilerplate example Next.js projects.
            </Typography>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <Typography component="h2">Deploy &rarr;</Typography>
            <Typography>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Typography>
          </a>
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Box>
  );
};

export default Home;
