import React from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  TextField,
  Container,
  Grid,
} from '@mui/material';
import LinearProgress, {
  LinearProgressProps,
} from '@mui/material/LinearProgress';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import {
  createContext,
  useContext,
  useMemo,
  useEffect,
  ReactNode,
} from 'react';

export const isBrowser = typeof window !== 'undefined';
/*export const wsInstance = isBrowser
  ? new WebSocket('ws://localhost:8000/ws')
  : null;*/

const Home: NextPage = ({}) => {
  let progress = 0;

  const wsInstance = useMemo(
    () => (isBrowser ? new WebSocket('ws://localhost:8000/ws') : null),
    [],
  );

  const [message, setMessage] = React.useState('');

  const [messages, setMessages] = React.useState<string[]>([]);

  const [connected, setConnected] = React.useState(false);

  useEffect(() => {
    if (wsInstance) {
      wsInstance.onopen = () => {
        console.log('connected');
        setConnected(true);
      };

      wsInstance.onmessage = (e) => {
        console.log('message', e.data);
        setMessages((messages) => [...messages, e.data]);
      };

      wsInstance.onclose = () => {
        console.log('disconnected');
        setConnected(false);
      };
    }
  }, [wsInstance]);

  function sendMessage() {
    if (wsInstance) {
      wsInstance.send(message);
      setMessage('');
    }
  }

  return (
    <Box className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box>
          {messages.map((message, index) => (
            <Box key={index}>{message}</Box>
          ))}
          <input
            className="input-chat"
            type="text"
            placeholder="Chat message ..."
            onChange={(e) => setMessage(e.target.value)}
            value={message}
          ></input>
          <button className="submit-chat" onClick={sendMessage}>
            Send
          </button>
        </Box>
        <Typography component="h1" className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Typography>
        <Button variant="contained">Send</Button>
        <Typography className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </Typography>
        <Box>
          {connected ? (
            <Typography variant="h6" color="success">
              Connected
            </Typography>
          ) : (
            <Typography variant="h6" color="error">
              Disconnected
            </Typography>
          )}
        </Box>
        <Container maxWidth="md">
          <Grid container spacing={2}>
            <Grid item xs={12} sm={12}>
              <LinearProgress variant="buffer" value={progress} />
              <Typography variant="h6" color="primary">
                {progress}%
              </Typography>
            </Grid>
            <Grid item xs={12} sm={12}>
              <Button variant="contained">Test</Button>
            </Grid>
          </Grid>
        </Container>
        <Container maxWidth="xs">
          <Grid container spacing={2}>
            <Grid item xs={12}>
              <h2>Form Demo</h2>

              <TextField
                value=""
                label={'Text Value'} //optional
                size={'small'} //optional
              />
            </Grid>
            <Grid item md={6}>
              <Button variant="contained">Submit</Button>
            </Grid>
            <Grid item md={6}>
              <Button variant="outlined">Reset</Button>
            </Grid>
          </Grid>
        </Container>
        <Box className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <Typography component="h2">Documentation &rarr;</Typography>
            <Typography>
              Find in-depth information about Next.js features and API.
            </Typography>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <Typography component="h2">Learn &rarr;</Typography>
            <Typography>
              Learn about Next.js in an interactive course with quizzes!
            </Typography>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <Typography component="h2">Examples &rarr;</Typography>
            <Typography>
              Discover and deploy boilerplate example Next.js projects.
            </Typography>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <Typography component="h2">Deploy &rarr;</Typography>
            <Typography>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Typography>
          </a>
        </Box>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Box>
  );
};

export default Home;
